//separate Class for to test HtelRoom class;
public class Hoteltest {
    public static void main(String[] args) {
        //creating Room1......................................
        HotelRoom room1 = new HotelRoom(101,"Suite",250.0,true,"Sunrise Hotel");
        // Creating Room2....................................................
        HotelRoom room2 = new HotelRoom(202,"Double",120.0,false,"Sunrise Hotel");
        //To display the Room1 Information......................
        room1.displayRoomInfo();
        //to Display Room2 Info..................................
        room2.displayRoomInfo();
        //to chek room availability..............................
        room1.checkAvailability();
    }
}
